language: go

go:
- "1.11"
- "1.12"
- master

# sudo is required for docker
sudo: required

# Enable docker
services:
- docker

before_install:
- go get github.com/ory/dockertest
- go get github.com/stretchr/testify
- go get github.com/mjibson/esc/...
