# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/HouzuoGuo/tiedot"
  version = "3.4.0"

[[constraint]]
  name = "github.com/alexcesaro/statsd"
  version = "2.0.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.36"

[[constraint]]
  branch = "master"
  name = "github.com/blevesearch/bleve"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/ghetzel/cli"
  version = "1.16.0"

[[constraint]]
  branch = "master"
  name = "github.com/ghetzel/diecast"

[[constraint]]
  branch = "master"
  name = "github.com/ghetzel/go-stockutil"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/guregu/dynamo"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  name = "github.com/husobee/vestigo"
  version = "1.0.2"

[[constraint]]
  name = "github.com/jbenet/go-base58"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/op/go-logging"

[[constraint]]
  branch = "master"
  name = "github.com/orcaman/concurrent-map"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.3.0"
